### ISSUE TITLE
iOS14 NSInternalInconsistencyException crash

### ISSUE THREAD

**Issue by nick-sturrock** [Gruveo/gruveo-ios-sdk#10] opened 2021-03-17 12:38 UTC
Since iOS14.3 we're having a crash from the Gruveo SDK, although we don't have a fully instrumented crash report because we don't have a symbolicated version of the lib so we can't say exactly which function was being called at the time. It's giving us a 'Fatal Exception: NSInternalInconsistencyException - Call must be made on main thread' apparently when it's accessing user preferences. Call stack is as follows:

Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x1a00db9d8 __exceptionPreprocess
1  libobjc.A.dylib                0x1b4461b54 objc_exception_throw
2  CoreFoundation                 0x19ffea50c -[CFPrefsSearchListSource addManagedSourceForIdentifier:user:]
3  Foundation                     0x1a12e4878 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:]
4  UIKitCore                      0x1a2945298 -[UIApplication _performBlockAfterCATransactionCommits:]
5  UIKitCore                      0x1a2292780 +[UIViewController _scheduleTransition:]
6  UIKitCore                      0x1a217dbac +[UIPresentationController _scheduleTransition:]
7  UIKitCore                      0x1a2177818 -[UIPresentationController runTransitionForCurrentState]
8  UIKitCore                      0x1a2175048 -[UIPresentationController _dismissWithAnimationController:interactionController:target:didEndSelector:]
9  UIKitCore                      0x1a229a65c -[UIViewController _dismissViewControllerWithAnimationController:interactionController:completion:]
10 UIKitCore                      0x1a2299a58 -[UIViewController _dismissViewControllerWithTransition:from:completion:]
11 UIKitCore                      0x1a2299220 -[UIViewController dismissViewControllerWithTransition:completion:]
12 UIKitCore                      0x1a2298c88 -[UIViewController dismissViewControllerWithTransition:completion:]
13 UIKitCore                      0x1a2298550 -[UIViewController _performCoordinatedPresentOrDismiss:animated:]
14 UIKitCore                      0x1a229b140 -[UIViewController dismissViewControllerAnimated:completion:]
15 GruveoSDK                      0x105c7f744 (Missing)
16 GruveoSDK                      0x105c87194 (Missing)
17 GruveoSDK                      0x105ca6414 (Missing)
18 WebRTC                         0x106e0ef64 (Missing)
19 WebRTC                         0x106e6f4d8 (Missing)
20 WebRTC                         0x106d60524 (Missing)
21 WebRTC                         0x106cf9ba0 (Missing)
22 WebRTC                         0x106cf9b1c (Missing)
23 libsystem_pthread.dylib        0x1e7c4bc9c _pthread_start
24 libsystem_pthread.dylib        0x1e7c50880 thread_start

Please advise whether this is a known issue, and if so whether there's a resolution or fix in the works.

**Comment by artmatsak** [comment] 2021-03-17 12:50
Thank you for reporting this. We'll look into the issue and be back with updates.

**Comment by ZombieMK** [comment] 2021-03-26 08:15
Thank you for your feedback. We’re working on rolling out a new SDK version that should fix this.

**Comment by Adeelhussainios** [comment] 2021-04-02 06:21
Hi, Art/Zombie, I just wanted to check how soon a the new SDK version would be rolled out as this is impacting a lot of our users using your service.

**Comment by artmatsak** [comment] 2021-04-02 10:38
We have prioritized the new iOS SDK version internally and expect to roll it out in the coming week or two.

**Comment by aaqibn** [comment] 2021-04-16 06:32
Hey guys,

Do, we have an update?

Thanks!

**Comment by artmatsak** [comment] 2021-04-16 16:58
Sorry about the delay with this. We've run into some issues with the SDK update but it's prioritized internally and we expect to be able to roll out the new version shortly.

**Comment by artmatsak** [comment] 2021-04-20 09:26
We have just rolled out version 1.5 of the iOS SDK. Please update and let us know if the issue is now fixed. Thanks!

**Comment by aaqibn** [comment] 2021-04-21 06:11
Thanks, this seems to be fixed now. we shall let you know if our users experience any other issues.

**Closed as completed** 2021-04-21 09:38 UTC
