### ISSUE TITLE
Voice issues in iOS version 12

### ISSUE THREAD

**Issue by RuttabHaroon** [Gruveo/gruveo-ios-sdk#11] opened 2021-03-19 12:13 UTC
Gruveo version : 1.4

**Problem occurring on:**
Software Version: 12.4.8
Device: iPhone 6

**Problem:**
I am getting voice issues in my iphone 6. 

When i turn on the speaker the person i am video calling can not hear my voice voice and when i am turn off off the speaker the opposite happens. The person i am video calling can hear my voice when the speaker is off. I have also tested on iOS 14 and it works fine on it. 

By speaker, i am talking about the white speaker button on the top right

Can you please check this?

**Comment by ZombieMK** [comment] 2021-03-26 08:16
Thank you for your feedback. We’re working on rolling out a new SDK version that should fix this.

**Comment by artmatsak** [comment] 2021-04-20 09:26
We have just rolled out version 1.5 of the iOS SDK. Please update and let us know if the issue is now fixed. Thanks!

**Comment by artmatsak** [comment] 2021-04-26 10:17
Closing, please feel free to reopen if the issue persists.

**Closed as completed** 2021-04-26 10:17 UTC
